In [2]:
print("Hi")
import torch

Hi


In [3]:
#Vector

scalar = torch.tensor(6)
scalar


tensor(6)

In [4]:
scalar.item()

6

In [5]:
vector = torch.tensor([7 , 7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
#Matrix 

MATRIX = torch.tensor([[7 , 8] , 
                       [6 , 7],
                       [9 , 10]])
MATRIX

tensor([[ 7,  8],
        [ 6,  7],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX[1]

tensor([6, 7])

In [11]:
MATRIX.shape

torch.Size([3, 2])

In [12]:
# TENSOR

TENSOR = torch.tensor( [ [ [1 , 2 , 3] , [2 , 3, 4]],
                        [[1 , 2, 3 ]  , [3 , 4 ,5]]])
TENSOR.shape


torch.Size([2, 2, 3])

### Random Tensor

Why random tensors ?
     Random tensors are important because the way
     neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [13]:
# Create a random tensor of size (3 , 4)
random_tensor = torch.rand( 3, 4)

random_tensor

# Well it creates a tensor of size of 3*4 with random constant  between 1 and 0

tensor([[0.3398, 0.0760, 0.9633, 0.9868],
        [0.2942, 0.8930, 0.5913, 0.9071],
        [0.6628, 0.6635, 0.0574, 0.0676]])

In [14]:
random_image_size_tensor = torch.rand(size=(224 , 224 ,3)) # height , width , color channels
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [15]:
# Creating tensor with the ones and the zeros 
zeros = torch.zeros(size=(3 , 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3 ,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype , zeros.dtype

(torch.float32, torch.float32)

In [18]:
# Creating a tensor range and tensors like other tensors
torch.range(0 , 10)

/tmp/ipykernel_109377/1958518427.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0 , 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
torch.__version__

'2.11.0+cpu'

In [20]:
one_to_ten = torch.arange(1 , 11)
one_to_ten.shape  # torch.arange( start , end , steps)

torch.Size([10])

In [21]:
ones_to_tens= torch.arange(1 , 21 , 2)
ones_to_tens.shape

torch.Size([10])

In [22]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#Dealing with tensor data types
float_32_tensor = torch.tensor([3.0  , 6.0 , 9.2],
                               dtype=None , device = None , requires_grad= False)
# what is datatype is tensor
float_32_tensor

tensor([3.0000, 6.0000, 9.2000])

In [24]:
float_32_tensor.dtype
# torch.float32 is default

torch.float32

# Getting information from tensors

 1. Tensor not right datatypes - to do get datatypes from a tensor , can use tensor.dtype

 2. Tensors not right shape - to get shape from a tensor , can use tensor.shape

 3. Tensors not on the right device - to get device from a tensor , we can tensor.device

In [25]:
## Getting Tensor Attributes

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2171, 0.1804, 0.7532, 0.8298],
        [0.1324, 0.3793, 0.8295, 0.3370],
        [0.6495, 0.5879, 0.8169, 0.3251]])

In [26]:
some_tensor.size , some_tensor.shape 

(<function Tensor.size>, torch.Size([3, 4]))

In [27]:
some_tensor.size()

torch.Size([3, 4])

In [28]:
print( some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor :  {some_tensor.shape} ")

print(f"Device tensor is on :{some_tensor.device}")

tensor([[0.2171, 0.1804, 0.7532, 0.8298],
        [0.1324, 0.3793, 0.8295, 0.3370],
        [0.6495, 0.5879, 0.8169, 0.3251]])
Datatype of tensor : torch.float32
Shape of tensor :  torch.Size([3, 4]) 
Device tensor is on :cpu


### Manpulating Tensor (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

# Create a tensor


In [29]:
tensor = torch.tensor( [ 1 , 2 , 3])
tensor + 10 

tensor([11, 12, 13])

In [30]:
tensor_1 = torch.zeros(8 , 25 , 25)

In [31]:
torch.manual_seed(42)
tensor_2 = torch.rand(size=(1 , 25 , 25))
tensor_2

tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
          0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294,
          0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317,
          0.1053],
         [0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860,
          0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343,
          0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539,
          0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913,
          0.8913, 0.1447, 0.5315, 0.1587, 0.6542, 0.3278, 0.6532, 0.3958,
          0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874,
          0.0041],
         [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653,
          0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057,
          0.3725, 0.7980, 0.8399, 0.1374, 0.2331, 0.9578, 0.3313, 0.3227,
          0.0162],
         [0.2137, 0.6249, 0.4340, 0.

Broadcasting , it allows in the pytroch(numpy) to make a operations without repeating itself 


Broadcasting compares shapes element-wise from the right (trailing dimensions). Two dimensions are compatible if:

They are equal, or
One of them is 1

In [32]:
tensor_1 + tensor_2 


tensor([[[0.8823, 0.9150, 0.3829,  ..., 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994,  ..., 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165,  ..., 0.9811, 0.0874, 0.0041],
         ...,
         [0.3882, 0.7410, 0.3636,  ..., 0.1931, 0.6907, 0.9170],
         [0.3513, 0.3546, 0.7670,  ..., 0.0599, 0.8489, 0.5579],
         [0.2305, 0.7613, 0.0268,  ..., 0.0848, 0.2203, 0.4898]],

        [[0.8823, 0.9150, 0.3829,  ..., 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994,  ..., 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165,  ..., 0.9811, 0.0874, 0.0041],
         ...,
         [0.3882, 0.7410, 0.3636,  ..., 0.1931, 0.6907, 0.9170],
         [0.3513, 0.3546, 0.7670,  ..., 0.0599, 0.8489, 0.5579],
         [0.2305, 0.7613, 0.0268,  ..., 0.0848, 0.2203, 0.4898]],

        [[0.8823, 0.9150, 0.3829,  ..., 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994,  ..., 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165,  ..., 0.9811, 0.0874, 0.

In [33]:
## Multiply tensor by scalar 
tensor*10

tensor([10, 20, 30])

In [34]:
## Try out Pytorch in-built
# Element-wise multiplication requires compatible shapes.

mul1 = torch.rand(size=(2, 3))
mul2 = torch.rand(size=(2, 3))

mul_final = torch.mul(mul1, mul2)

# For matrix multiplication, use shapes (2, 3) and (3, 2).
matmul2 = torch.rand(size=(3, 2))
matmul_final = torch.matmul(mul1, matmul2)
matmul_final

## matmul and mul is different 

tensor([[0.2370, 0.9343],
        [0.2580, 0.5497]])

In [35]:
mul_final , matmul_final 

(tensor([[0.0485, 0.3031, 0.6314],
         [0.0040, 0.1911, 0.0081]]),
 tensor([[0.2370, 0.9343],
         [0.2580, 0.5497]]))

In [36]:
torch.manual_seed(42)
tensor = torch.rand(size=(3 , 2 , 2))


value = 0
for i in range(len(tensor)):
    value += tensor[i]

value  # it will iterate for the first index of the shape and making the output 
    # such as [[], []]

tensor([[2.2135, 1.6491],
        [1.5740, 2.3465]])

In [37]:
tensor

tensor([[[0.8823, 0.9150],
         [0.3829, 0.9593]],

        [[0.3904, 0.6009],
         [0.2566, 0.7936]],

        [[0.9408, 0.1332],
         [0.9346, 0.5936]]])

In [38]:
for i in range(len(tensor)):
    print(f" The value of len(tensor) is {len(tensor)}")
    print (f" For the givem value of  {i} find the value {tensor[i]} ")

 The value of len(tensor) is 3
 For the givem value of  0 find the value tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]]) 
 The value of len(tensor) is 3
 For the givem value of  1 find the value tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]]) 
 The value of len(tensor) is 3
 For the givem value of  2 find the value tensor([[0.9408, 0.1332],
        [0.9346, 0.5936]]) 


In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]

print(value)

tensor([[1.8159, 1.2160],
        [1.0859, 1.9025]])
CPU times: user 2.44 ms, sys: 0 ns, total: 2.44 ms
Wall time: 2.17 ms


In [40]:
%%time
torch.matmul( tensor , tensor)

# matrix multiplication (part2) : The Two main rules of matrix multiplication

CPU times: user 673 µs, sys: 67 µs, total: 740 µs
Wall time: 466 µs


tensor([[[1.1287, 1.6850],
         [0.7051, 1.2706]],

        [[0.3066, 0.7115],
         [0.3038, 0.7840]],

        [[1.0095, 0.2044],
         [1.4340, 0.4768]]])

The rule for matrix multiplication for more that 3-dimensional matrix 
    
    for 3D+ tensors, matrix multiplication (torch.matmul or @) splits the shape into two parts: the last two dimensions (the actual matrix) and everything before that (the batch dimensions)

    Rule 1 : Last two dims → standard matrix-multiply rule still applies: c1 == r2 (non-negotiable, same as 2D) (..... , r1 , c1)  (...... , r2 , c2)

        (....... , r1 , c2)

    Rule 2 : Batch dims (everything before the last two) → must be broadcastable with each other using the same broadcasting rules from before (equal, or one of them is 1)

    

In [41]:
## Tensor shape errors

tensor_A = torch.tensor([[1 , 2],
                         [3 , 4],
                         [5 , 6]])


tensor_B = torch.tensor([[7 , 10],
                         [8 , 11],
                         [9 , 12]])

print(tensor_A.shape , tensor_B.shape)

torch.Size([3, 2]) torch.Size([3, 2])


# Transpose a Matrix

In [42]:
## 1 .t() - classic 2D-only transpose

T_tensor = torch.rand(size=(3 , 5))

T_tensor.t()

tensor([[0.8694, 0.5739, 0.2969],
        [0.5677, 0.2666, 0.8317],
        [0.7411, 0.6274, 0.1053],
        [0.4294, 0.2696, 0.2695],
        [0.8854, 0.4414, 0.3588]])

In [43]:
## 2 .T property - same as .t() for 2D , but reverses all dims for higher-D  ( 3,5) ->(5 ,3)   (2 , 3 , 5) -> (5 , 3 , 2)
## warns - reverses every dimension
T_tensor = torch.rand(size=(2 , 3 , 5))
T_tensor.T

print(T_tensor.shape)

##3 .transpose(dim0 , dim1) / torch.transpose( input , dim0 , dim1) - swap any 2 dims
T_tensor = torch.rand(size=(3 , 4 , 2))
T_tensor=T_tensor.transpose(0,2)

T_tensor.shape

torch.Size([2, 3, 5])


/tmp/ipykernel_109377/3534891664.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  T_tensor.T


torch.Size([2, 4, 3])

In [44]:
T_tensor = torch.rand(size=(2 , 1, 3))
T_tensor = torch.transpose(T_tensor ,1 , 2 )
## if we don't put T=torch.transpose() the Matrix in down the line 
## is not same 
T_tensor.shape

torch.Size([2, 3, 1])

In [45]:
## inplace=True shows up on things like nn.Relu , nn.LeakyRelu , nn.ELU , nn.SELU , nn.Dropout

## Finding min , max , sum  Aggregartion in the tensor 
## Create a tensor

x = torch.arange(0 , 100 , 10)
x



tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [47]:
#Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean 
# input dtype should be either floating point or complex dtypes
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()

tensor(45.)

In [49]:
#Find the sum 
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [50]:
# Finding the argmax , argmin  -- return the index of the min / max index value in the system 
print(f"print the index with max value {x.argmax()}")
print(f"print the index with min value {x.argmin()}")

print the index with max value 9
print the index with min value 0


In [51]:
## Reshaping , stacking ,  viewing and stacking Tensors
# Reshaping - reshapes an input tensor to a defined shape

# View - Return a view of an input tensor of certain shape but keep the same memory
# Stacking - Combine multiple tensors onn top of each other (vs stack ) or side by side (hstack)


# Reshaping 
torch.manual_seed(42)

a = torch.arange(1 , 10)
print(f" the original A value {a}")
a=a.reshape( 3 , 3) # 9 elements have being rearranged
print(f"the element rearranged after some times {a}")
a.reshape( 3 , -1) ##Imp feature

## flatten images for a Linear 

image = torch.rand(size=(3 , 2 , 2 , 2))
print(f"The image before we flatten the dimensions {image}")

image=image.reshape(image.size(0) , -1)
print(f"After the change flatten as occured the shape {image.shape}")
print(image)



 the original A value tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
the element rearranged after some times tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The image before we flatten the dimensions tensor([[[[0.8823, 0.9150],
          [0.3829, 0.9593]],

         [[0.3904, 0.6009],
          [0.2566, 0.7936]]],


        [[[0.9408, 0.1332],
          [0.9346, 0.5936]],

         [[0.8694, 0.5677],
          [0.7411, 0.4294]]],


        [[[0.8854, 0.5739],
          [0.2666, 0.6274]],

         [[0.2696, 0.4414],
          [0.2969, 0.8317]]]])
After the change flatten as occured the shape torch.Size([3, 8])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274, 0.2696, 0.4414, 0.2969, 0.8317]])


In [52]:
image_2 = torch.rand(size=(3 , 1 , 2 , 2))
print(f"the image_2 {image_2}")

image_2 =image_2.reshape(image_2.size(0) , image_2.size(1) , -1)
print(f"After the flatten as occured {image_2.shape}")
print(image_2)


image_3 = torch.rand(size=(5,))
print(f"After the 3rd image is found {image_3}")
image_3 = image_3.reshape(-1 , 1)

print(f"After the new dimension added shape : -{image_3.shape}")
print(image_3)

#reshape() (like view(), transpose(), stack(), etc.) does not modify the tensor in place — it returns a brand-new
#  tensor/view. If you don't capture that return value with =, the operation still runs, but the result just... evaporates.


the image_2 tensor([[[[0.1053, 0.2695],
          [0.3588, 0.1994]]],


        [[[0.5472, 0.0062],
          [0.9516, 0.0753]]],


        [[[0.8860, 0.5832],
          [0.3376, 0.8090]]]])
After the flatten as occured torch.Size([3, 1, 4])
tensor([[[0.1053, 0.2695, 0.3588, 0.1994]],

        [[0.5472, 0.0062, 0.9516, 0.0753]],

        [[0.8860, 0.5832, 0.3376, 0.8090]]])
After the 3rd image is found tensor([0.5779, 0.9040, 0.5547, 0.3423, 0.6343])
After the new dimension added shape : -torch.Size([5, 1])
tensor([[0.5779],
        [0.9040],
        [0.5547],
        [0.3423],
        [0.6343]])


In [56]:
# Stacking - torch.stack(tensors, dim=0)

# Combines tensors along a brand-new dimension. All tensors must have identical shapes.

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([7, 8, 9])

horizontal_stack = torch.stack([a, b, c], dim=0)  # (3, 3): each tensor becomes a row
vertical_stack = torch.stack([a, b, c], dim=1)  # (3, 3): each tensor becomes a column

print(f"The horizontal stack:\n{horizontal_stack}")
print(f"The vertical stack:\n{vertical_stack}")

The horizontal stack:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
The vertical stack:
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [59]:
torch.manual_seed(42)

a = torch.rand(1 , 3 , 1 , 5)
a

tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904]],

         [[0.6009, 0.2566, 0.7936, 0.9408, 0.1332]],

         [[0.9346, 0.5936, 0.8694, 0.5677, 0.7411]]]])

In [ ]:
a.squeeze() ## Note the element count remain same but the dimension with only 1 dimension value is being removed


tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])

In [64]:
b= torch.rand(size=(2 , 3))
b


tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [ ]:
c=b.squeeze(0)  # squeeze(0) removes dimension 0 only if its size is 1. Here, dimension 0 has size 2, so nothing changes:
c.shape  
# Hence , Yes. squeeze(dim) removes the specified dimension only when its size is exactly 1.

torch.Size([2, 3])

In [67]:
# Unsequeeze dimensions
# Unlike squeeze, dim is mandatory — there's no argument-free version, because "add a dimension" is meaningless without saying where.

a = torch.tensor([1 , 2 , 3])  #(3 ,)
a.unsqueeze(0)  #->(1 , 3)  new dim at the front
a.unsqueeze(1) #-> (3 ,1)  new dim at the END ( for a 1D tensor)
a.unsqueeze(-1) # -> (3 , 1) same as above , negative-indexed


tensor([[1],
        [2],
        [3]])